"""Initial migration

Revision ID: fdda887dea08
Revises: 
Create Date: 2026-05-05 13:02:08.438147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdda887dea08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('horario_inicio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('horario_fim',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=False)

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('login',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('papel',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('papel',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('login',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('horario_fim',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('horario_inicio',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('data',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
